services:
  backend:
    build:
      context: ./tagtic-demo-api
    container_name: tagtic-api
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - ./tagtic-demo-api/.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./tagtic-demo-web
    container_name: tagtic-web
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend